### PR TITLE
Visualization fixes

### LINKED ISSUE #590: [BUG] Visualisation glitch on `MarkdownString` components
One of my steps saves an artifact which is a `MarkdownString` element, using the `StructuredString` materialiser. In the visualisation, the background and the text color are almost identical, making it almost impossible to read the text.

This is how the visualization looks like:
image

The text can be read when selected, but looks invisible in the default view: 
image

### PR DESCRIPTION
**Pull request by Cahllagerfeld**
closes #590

### CODE REVIEW

File: src/components/artifacts/MarkdownVisualization.tsx [hunk 1]
```diff
@@ -2,5 +2,5 @@ import { Props } from "./Visualization";
 import Markdown from "react-markdown";
 
 export default function MarkdownVisualization({ content }: Props) {
-	return <Markdown className="prose max-w-none">{content}</Markdown>;
+	return <Markdown className="!prose !max-w-none">{content}</Markdown>;
```
Comment (Cahllagerfeld) [inline src/components/artifacts/MarkdownVisualization.tsx:5]: There was an css override happening, due to an external stylesheet. With the exclamation mark it gets important, so the styles arent overwrittena nymore

**Review by atzin-escandia — APPROVED** [review]
